# Generated by Django 4.0.4 on 2022-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Popolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
