# Generated by Django 4.0.3 on 2022-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Popolapp', '0002_alter_questions_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=100, null=True)),
                ('request_phone_number', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
