# Generated by Django 4.0.3 on 2022-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Popolapp', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('contact_email', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_picture_title', models.CharField(max_length=30, null=True)),
                ('first_picture_discription', models.CharField(max_length=100, null=True)),
                ('second_picture_title', models.CharField(max_length=30, null=True)),
                ('second_picture_discription', models.CharField(max_length=100, null=True)),
                ('third_picture_title', models.CharField(max_length=30, null=True)),
                ('fourth_picture_title', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
