# Generated by Django 4.0.3 on 2022-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Popolapp', '0004_contact_items_main_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_screen',
            name='first_picture_title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='main_screen',
            name='fourth_picture_title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='main_screen',
            name='second_picture_title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='main_screen',
            name='third_picture_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
