# Generated by Django 4.0.3 on 2022-06-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Popolapp', '0005_alter_main_screen_first_picture_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_screen',
            name='fourth_picture_title',
        ),
        migrations.RemoveField(
            model_name='main_screen',
            name='third_picture_title',
        ),
    ]
